version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - $(aws ecr get-login --region us-east-2 --no-include-email)
    
  build:
    commands:
    - echo Build started on `date`
    - echo Building Java
    - cd AuditSeverity-Microservice
    - mvn compile
    - mvn package -DskipTests
    - echo Building the docker image..
    - docker build -t service/severity .
    
    - docker tag service/severity 222512976514.dkr.ecr.us-east-2.amazonaws.com/auditseverity:severity
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing docker image
    - docker push 222512976514.dkr.ecr.us-east-2.amazonaws.com/auditseverity:severity
    - echo Writting definition file
    - printf '[{"name":"severity-container","imageUri":"%s"}]' 222512976514.dkr.ecr.us-east-2.amazonaws.com/auditseverity:severity > imagedefinitions.json
artifacts:
  files:
  - AuditSeverity-Microservice/imagedefinitions.json
